# Generated by Django 4.2.7 on 2023-11-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='review.category'),
        ),
    ]
