# Generated by Django 4.2.7 on 2023-11-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
