# Generated by Django 4.2.7 on 2023-11-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='excerpt',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
