# Generated by Django 4.2.7 on 2023-11-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_review_excerpt_alter_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='excerpt',
            field=models.TextField(max_length=150),
        ),
    ]
